Server/spf_sales/spf_sales/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spf_sales.views.home', name='home'),
    # url(r'^spf_sales/', include('spf_sales.foo.urls')),
     
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^factoryState/', include('factoryState.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^command/', 'command.views.command'),
     url(r'^json/', 'command.views.json'),
     url(r'^interface/', 'command.views.interface'),
     url(r'^testing/', 'command.views.testing'),
     url(r'^startup/', 'command.views.startup'),
     url(r'^order/', 'order.views.order'),
     url(r'^latestCommand/', 'command.views.latestCommand'),
     url(r'^differentCommands/', 'command.views.newCommands'),
     url(r'^tinyGParameter/', 'command.views.tinyGParameter'),
     url(r'^factoryState/', 'command.views.factoryState'),

)

Server/spf_sales/command/models.py
from django.db import models
from django.forms import ModelForm
from factoryState.models import FactoryState
from django.template.loader import render_to_string

class Command(models.Model):
    command  =   models.CharField(max_length=20)
    commandTimeStamp    =   models.DateTimeField(auto_now=True)
    parameter=models.FloatField()
    quantity=models.IntegerField()
    status      =   models.CharField(max_length=20)
    statusTimeStamp   =   models.DateTimeField(auto_now=True)
    description = models.TextField()
    json = models.TextField()

    def __unicode__(self):
        return self.command

Server/spf_sales/order/models.py
from django.db import models
from django.forms import ModelForm

class Order(models.Model):
    customerid  =   models.CharField(max_length=20)
    voltage     =   models.IntegerField()
    current     =   models.IntegerField()
    width       =   models.IntegerField()
    height      =   models.IntegerField()
    order_ts    =   models.DateTimeField(auto_now=True)
    status      =   models.CharField(max_length=20)
    status_ts   =   models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

class OrderForm(ModelForm):
    class Meta:
        model = Order

Server/spf_sales/command/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from command.models import Command
from factoryState.models import FactoryState
from django.utils import timezone

def command(request):
        if request.method == 'POST':
		_command=request.POST.get('command', 'boo')
		_parameter=request.POST.get('parameter',0)
		_quantity=request.POST.get('quantity',0)
		myCommand = Command(command=_command, statusTimeStamp=timezone.now(), parameter=_parameter, quantity=_quantity, status='queued', commandTimeStamp=timezone.now())
		myCommand.json=jsonTranslation(myCommand)
		if myCommand.command=="placePanel":
			myCommand.description=buildDescription(myCommand)
                myCommand.save()
                return HttpResponse("yo")
	else:
		return HttpResponse("bite me")

def buildDescription(_command):
	if FactoryState.objects.exists():  #assuming we have a factoryState object, pass it to the appropriate json template, render the template, and pass it back, to get stored along with the command
		factoryState=FactoryState.objects.get(id=1)
		description=render_to_string("panelDescription.html", {'command': _command, 'factoryState' : factoryState})
	else:
		description="aaa"
	return description

def jsonTranslation(_command):
	if FactoryState.objects.exists():  #assuming we have a factoryState object, pass it to the appropriate json template, render the template, and pass it back, to get stored along with the command
		factoryState=FactoryState.objects.get(id=1)
		jsonString=render_to_string(_command.command + ".html", {'command': _command, 'factoryState' : factoryState})
	else:
		jsonString=""
	return jsonString

def json(request):
	_command="placeSolette"
	if FactoryState.objects.exists():  #assuming we have a factoryState object, pass it to the appropriate json template, render the template, and pass it back, to get stored along with the command
		factoryState=FactoryState.objects.get(id=1)
		jsonString=render_to_string(_command + ".html", {'command': _command, 'factoryState' : factoryState})
	else:
		jsonString=""
	responseString=_command+" "+jsonString
	return HttpResponse(responseString)

def latestCommand(request):
	return HttpResponse("bluh")

def tinyGParameter(request):
        if request.method == 'POST':
		_command=request.POST.get('command', 'boo')
		_parameter=request.POST.get('parameter',0)
		factoryState=FactoryState.objects.get(id=1)
		if _command.find('var_')!=-1:
			setattr(factoryState, _command, _parameter)
			_command=_command[4:]
			factoryState.save()
		myCommand = Command(command=_command, statusTimeStamp=timezone.now(), quantity=0,parameter=_parameter, status='queued', commandTimeStamp=timezone.now())
		myCommand.json=render_to_string("parameter.html", {'command': myCommand})
                myCommand.save()
                return HttpResponse("parameter set")
	else:
		return HttpResponse("poo")

def factoryState(request):
        if request.method == 'POST':
		_command=request.POST.get('command', 'boo')
		_parameter=request.POST.get('parameter',0)
		factoryState=FactoryState.objects.get(id=1)
		setattr(factoryState, _command, _parameter)
		factoryState.save()
		return HttpResponse("factory settings updated")
	else:
		return HttpResponse("poo")

def newCommands(request):
	if Command.objects.filter(status='queued').order_by('-commandTimeStamp').exists():
		latestCommands=Command.objects.filter(status='queued').order_by('-commandTimeStamp')
		for command in latestCommands:
			command.status= "loaded onto pi"
			command.statusTimeStamp=timezone.now()
			command.save()
		return render(request, 'newCommands.html', { 'commands': latestCommands})
	else:
		return HttpResponse("queue_empty")

def interface(request):
	if FactoryState.objects.exists():  #assuming we have a factoryState object, pass it to the appropriate json template, render the template, and pass it back, to get stored along with the command
		factoryState=FactoryState.objects.get(id=1)
	return render(request, 'interface.html', {'factoryState' : factoryState})

def testing(request):
	if FactoryState.objects.exists():  #assuming we have a factoryState object, pass it to the appropriate json template, render the template, and pass it back, to get stored along with the command
		factoryState=FactoryState.objects.get(id=1)
	return render(request, 'testing.html', {'factoryState' : factoryState})

def startup(request):
	if FactoryState.objects.exists():  #assuming we have a factoryState object, pass it to the appropriate json template, render the template, and pass it back, to get stored along with the command
		factoryState=FactoryState.objects.get(id=1)
	return render(request, 'startup.html', {'factoryState' : factoryState})

Server/spf_sales/order/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from order.models import Order, OrderForm
from django.utils import timezone

def order(request):
        if request.method == 'POST':
            form = OrderForm(request.POST)
            if form.is_valid():
                _customerid  =   form.cleaned_data['customerid']
                _voltage     =   form.cleaned_data['voltage']
                _current     =   form.cleaned_data['current']
                _width       =   form.cleaned_data['width']
                _height      =   form.cleaned_data['height']
                _status      =   form.cleaned_data['status']

                job = Order(customerid=_customerid, voltage=_voltage, current=_current, width=_width, height=_height, status=_status, order_ts=timezone.now())
                job.save()

                return HttpResponse("thank you!")
            
            else:
                form = OrderForm()
                render(request, 'order.html', {
                        'form': form,
                        })

        else: 
            form = OrderForm()
            return render(request, 'order.html', {
               'form': form,
               })

def finished(request):
	return render(request, 'finished.html')

Server/spf_sales/templates/_order.html
<form action="/order/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Place Order" />
</form>

Server/spf_sales/templates/command.html
{{ command.command }}
{{ command.parameter }}

Server/spf_sales/templates/config.html
{{ command.command }}={{ command.parameter }}

Server/spf_sales/templates/finished.html
Boo!

Server/spf_sales/templates/latestCommand.html
{{ command.command }}<br/>
{{ command.parameter }}<br/>

Server/spf_sales/templates/newCommands.html
{# <b>command, parameter, quantity, timestamp, description, json </b><br/> #}{% for command in commands %}{{ command.command }},{{ command.parameter }},{{ command.quantity }},{{ command.commandTimeStamp|date:"M/d/Y h:m:s"}},{{ command.description }},{{ command.json }}<br/>{% endfor %}

Server/spf_sales/templates/order.html
<form action="/order/" method="post">{% csrf_token %}
<p><label for="id_customerid">CustomerID:</label>
    <input id="id_customerid" type="text" name="customerid" maxlength="20" /></p>
<p><label for="id_voltage">Voltage:</label>
    <input id="id_voltage" type="number" name="voltage" min="1" max="5"></p>
<p><label for="id_current">Current:</label>
    <input id="id_current" type="number" name="current" min="100" max="1000"></p>
<p><label for="id_width">Width:</label>
    <input id="id_width" type="number" name="width" min="1" max="20"></p>
<p><label for="id_height">Height:</label>
    <input id="id_height" type="number" name="height" min="1" max="10"></p>
<input type="hidden" name="status" value="PENDING">
<input type="submit" value="Place order" />
</form>

Server/spf_sales/templates/testing.html
<html>
<head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
<script src="http://solarpocketfactory.com/static/js/interface.js"></script>
<link rel="stylesheet" type="text/css" href="http://solarpocketfactory.com/static/css/testing.css">

</head>
<div class="buttons">
<div class="motionCommands">
<div id="placement">
  <div class="panelPlacement">
    <div class="panelButton">
      <input type="button" class="button" value="placePanel" onclick="panel($(this).val())" />
    </div>
    <div class="panelParameters">
      <input type="text" value="5" class="parameter" id="voltage"> volts
      <input type="text" value="1" class="parameter" id="quantity"> panels 
    </div>
  </div>      
  <input type="button" class="button" value="placeSolette" id="soletteButton" onclick="sendPost($(this).val())" />      
  
</div>

<div class="utility">
      <input type="button" class="button" value="vacuumOn" onclick="sendPost($(this).val())" />  
      <input type="button" class="button" value="vacuumOff" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="suctionOn" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="suctionOff" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="backingPusherIn" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="backingPusherOut" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="tabbingCutterUp" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="tabbingCutterDown" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="demo" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="bounceWithMe" onclick="sendPost($(this).val())" /> 
      <input type="button" class="button" value="startup" onclick="sendPost($(this).val())" /> 

      <input type="button" class="button" id="E-Stop"  value="E-stop" onclick="sendPost($(this).val())" /> 
</div>


<div class="factoryStateColumn2">
    
    #raw materials in stock<br/>
        <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="solettesInHopper"><input type="text"  value="{{ factoryState.solettesInHopper }}" id="solettesInHopper" class="factoryStateValue"></div>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="backingWidth"><input type="text"  value="{{ factoryState.backingWidth }}" id="backingWidth" class="factoryStateValue"></div>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="backingLength"><input type="text"  value="{{ factoryState.backingLength }}" id="backingLength" class="factoryStateValue"></div>


    #backing dimensions<br/>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="holeOffset"><input type="text"  value="{{ factoryState.holeOffset }}" id="holeLength" class="factoryStateValue"></div>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="holeLength"><input type="text"  value="{{ factoryState.holeLength }}" id="holeLength" class="factoryStateValue"></div>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="padLength"><input type="text"  value="{{ factoryState.padLength }}" id="padLength" class="factoryStateValue"></div>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="tabbingConnection"><input type="text"  value="{{ factoryState.tabbingConnection }}" id="tabbingConnection" class="factoryStateValue"></div>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="tabbingLength"><input type="text"  value="{{ factoryState.tabbingLength }}" id="tabbingLength" class="factoryStateValue"></div>

            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="soletteSpacing"><input type="text"  value="{{ factoryState.soletteSpacing }}" id="soletteSpacing" class="factoryStateValue"></div>    

    #solette dimensions<br/>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="soletteLength"><input type="text"  value="{{ factoryState.soletteLength }}" id="soletteLength" class="factoryStateValue"></div>
             <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="soletteWidth"><input type="text"  value="{{ factoryState.soletteWidth }}" id="soletteWidth" class="factoryStateValue"></div> 
             <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="soletteThickness"><input type="text"  value="{{ factoryState.soletteThickness }}" id="soletteThickness" class="factoryStateValue"></div>
 

    #factory dimensions<br/>
            <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="hopperPosition"><input type="text"  value="{{ factoryState.hopperPosition }}" id="hopperPosition" class="factoryStateValue"></div>
             <div class="valueLine"><input type="button" class="factoryStateButton" onClick="updateFactoryState($(this).val())" value="conveyorPosition"><input type="text"  value="{{ factoryState.conveyorPosition }}" id="conveyorPosition" class="factoryStateValue"></div>
 

</div>

</html>